config/routes.rb
Enciclofrutas::Application.routes.draw do
  resources :frutas

  resources :mercados

  resources :epocas

  resources :vitaminas

  resources :usuarios

  resources :moderadors

end

app/models/epoca.rb
class Epoca < ActiveRecord::Base
end

app/models/fruta.rb
class Fruta < ActiveRecord::Base
  belongs_to :moderador
  belongs_to :epoca
end

app/models/mercado.rb
class Mercado < ActiveRecord::Base
end

app/models/moderador.rb
class Moderador < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/models/vitamina.rb
class Vitamina < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/epocas_controller.rb
class EpocasController < InheritedResources::Base
end

app/controllers/frutas_controller.rb
class FrutasController < InheritedResources::Base
end

app/controllers/mercados_controller.rb
class MercadosController < InheritedResources::Base
end

app/controllers/moderadors_controller.rb
class ModeradorsController < InheritedResources::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < InheritedResources::Base
end

app/controllers/vitaminas_controller.rb
class VitaminasController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epocas_helper.rb
module EpocasHelper
end

app/helpers/frutas_helper.rb
module FrutasHelper
end

app/helpers/mercados_helper.rb
module MercadosHelper
end

app/helpers/moderadors_helper.rb
module ModeradorsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/vitaminas_helper.rb
module VitaminasHelper
end

app/views/epocas/_form.html.haml
= semantic_form_for(@epoca) do |f|
 = f.input :estacao_do_ano, :label => 'Estação do ano'

 
 = f.submit 'Salvar'

app/views/epocas/edit.html.erb
<h1>Editing epoca</h1>

<%= render 'form' %>

<%= link_to 'Show', @epoca %> |
<%= link_to 'Back', epocas_path %>

app/views/epocas/index.html.erb
<h1>Listing epocas</h1>

<table>
  <tr>
    <th>Estacao do ano</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @epocas.each do |epoca| %>
  <tr>
    <td><%= epoca.estacao_do_ano %></td>
    <td><%= link_to 'Show', epoca %></td>
    <td><%= link_to 'Edit', edit_epoca_path(epoca) %></td>
    <td><%= link_to 'Excluir', epoca, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Epoca', new_epoca_path %>

app/views/epocas/new.html.erb
<h1>New epoca</h1>

<%= render 'form' %>

<%= link_to 'Back', epocas_path %>

app/views/epocas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Estação do ano:</b>
  <%= @epoca.estacao_do_ano %>
</p>


<%= link_to 'Edit', edit_epoca_path(@epoca) %> |
<%= link_to 'Back', epocas_path %>

app/views/frutas/_form.html.haml
= semantic_form_for(@fruta) do |f|
  = f.input :nome, :label => 'Nome'
  = f.input :nome_cientifico, :label => 'Nome_Cientifico'
  = f.input :peso, :label => 'Peso'
  = f.input :cor, :label => 'Cor'
  = f.input :preco, :label => 'Preço'
  = f.input :localizacao, :label => 'Localização'
  = f.input :calorias, :label => 'Calorias'
  = f.input :informacao, :label => 'Informação'
  = f.input :moderador, :member_label => :nome, :label => 'Nome'
  = f.input :epoca, :member_label => :estacao_do_ano, :label => 'Estação do ano'
  
  = f.submit 'Salvar'

app/views/frutas/edit.html.erb
<h1>Editing fruta</h1>

<%= render 'form' %>

<%= link_to 'Show', @fruta %> |
<%= link_to 'Back', frutas_path %>

app/views/frutas/index.html.erb
<h1>Listing frutas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Nome cientifico</th>
    <th>Peso</th>
    <th>Cor</th>
    <th>Preco</th>
    <th>Localizacao</th>
    <th>Calorias</th>
    <th>Informacao</th>
    <th>Nome</th>
    <th>Estação do Ano</th> 
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @frutas.each do |fruta| %>
  <tr>
    <td><%= fruta.nome %></td>
    <td><%= fruta.nome_cientifico %></td>
    <td><%= fruta.peso %></td>
    <td><%= fruta.cor %></td>
    <td><%= fruta.preco %></td>
    <td><%= fruta.localizacao %></td>
    <td><%= fruta.calorias %></td>
    <td><%= fruta.informacao %></td>
    <td><%= fruta.moderador.nome %></td>
   <td><%= fruta.epoca.id %></td>
    <td><%= link_to 'Show', fruta %></td>
    <td><%= link_to 'Edit', edit_fruta_path(fruta) %></td>
    <td><%= link_to 'Excluir', fruta, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fruta', new_fruta_path %>

app/views/frutas/new.html.erb
<h1>New fruta</h1>

<%= render 'form' %>

<%= link_to 'Back', frutas_path %>

app/views/frutas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @fruta.nome %>
</p>

<p>
  <b>Nome_Cientifico:</b>
  <%= @fruta.nome_cientifico %>
</p>

<p>
  <b>Peso:</b>
  <%= @fruta.peso %>
</p>

<p>
  <b>Cor:</b>
  <%= @fruta.cor %>
</p>

<p>
  <b>Preço:</b>
  <%= @fruta.preco %>
</p>

<p>
  <b>Localização:</b>
  <%= @fruta.localizacao %>
</p>

<p>
  <b>Calorias:</b>
  <%= @fruta.calorias %>
</p>

<p>
  <b>Informação:</b>
  <%= @fruta.informacao %>
</p>

<p>
  <b>Nome:</b>
  <%= @fruta.moderador.nome %>
</p>

<p>
  <b>Estação do Ano:</b>
  <%= @fruta.epoca.estacao_do_ano %>
</p>


<%= link_to 'Edit', edit_fruta_path(@fruta) %> |
<%= link_to 'Back', frutas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enciclofrutas</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mercados/_form.html.haml
= semantic_form_for(@mercado) do |f|
 = f.input :nome, :label => 'Nome'
 = f.input :endereco, :label => 'Endereço'
 = f.input :telefone, :label => 'Telefone'
 = f.submit 'Salvar'

app/views/mercados/edit.html.erb
<h1>Editing mercado</h1>

<%= render 'form' %>

<%= link_to 'Show', @mercado %> |
<%= link_to 'Back', mercados_path %>

app/views/mercados/index.html.erb
<h1>Listing mercados</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mercados.each do |mercado| %>
  <tr>
    <td><%= mercado.nome %></td>
    <td><%= mercado.endereco %></td>
    <td><%= mercado.telefone %></td>
    <td><%= link_to 'Show', mercado %></td>
    <td><%= link_to 'Edit', edit_mercado_path(mercado) %></td>
    <td><%= link_to 'Excluir', mercado, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mercado', new_mercado_path %>

app/views/mercados/new.html.erb
<h1>New mercado</h1>

<%= render 'form' %>

<%= link_to 'Back', mercados_path %>

app/views/mercados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @mercado.nome %>
</p>

<p>
  <b>Endereço:</b>
  <%= @mercado.endereco %>
</p>

<p>
  <b>Telefone:</b>
  <%= @mercado.telefone %>
</p>


<%= link_to 'Edit', edit_mercado_path(@mercado) %> |
<%= link_to 'Back', mercados_path %>

app/views/moderadors/_form.html.haml
= semantic_form_for(@moderador) do |f|
 = f.input :nome, :label => 'Nome'
 = f.input :sobrenome, :label => 'Sobrenome'
 = f.input :senha, :label => 'Senha'
 = f.input :pais, :label => 'Pais'
 = f.input :cidade, :label => 'Cidade'
 = f.input :genero, :label => 'Genero'
 = f.input :data_nasc, :label => 'Data_Nasc'
 = f.input :cpf, :label => 'CPF'
 = f.input :rg, :label => 'RG'
 = f.input :email, :label => 'e-mail'
 
 = f.submit 'Salvar'

app/views/moderadors/edit.html.erb
<h1>Editing moderador</h1>

<%= render 'form' %>

<%= link_to 'Show', @moderador %> |
<%= link_to 'Back', moderadors_path %>

app/views/moderadors/index.html.erb
<h1>Listing moderadors</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Senha</th>
    <th>Pais</th>
    <th>Cidade</th>
    <th>Genero</th>
    <th>Data nasc</th>
    <th>Cpf</th>
    <th>Rg</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moderadors.each do |moderador| %>
  <tr>
    <td><%= moderador.nome %></td>
    <td><%= moderador.sobrenome %></td>
    <td><%= moderador.senha %></td>
    <td><%= moderador.pais %></td>
    <td><%= moderador.cidade %></td>
    <td><%= moderador.genero %></td>
    <td><%= moderador.data_nasc %></td>
    <td><%= moderador.cpf %></td>
    <td><%= moderador.rg %></td>
    <td><%= moderador.email %></td>
    <td><%= link_to 'Show', moderador %></td>
    <td><%= link_to 'Edit', edit_moderador_path(moderador) %></td>
    <td><%= link_to 'Excluir', moderador, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Moderador', new_moderador_path %>

app/views/moderadors/new.html.erb
<h1>New moderador</h1>

<%= render 'form' %>

<%= link_to 'Back', moderadors_path %>

app/views/moderadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @moderador.nome %>
</p>

<p>
  <b>Sobrenome:</b>
  <%= @moderador.sobrenome %>
</p>

<p>
  <b>Senha:</b>
  <%= @moderador.senha %>
</p>

<p>
  <b>Pais:</b>
  <%= @moderador.pais %>
</p>

<p>
  <b>Cidade:</b>
  <%= @moderador.cidade %>
</p>

<p>
  <b>Genero:</b>
  <%= @moderador.genero %>
</p>

<p>
  <b>Data_Nasc:</b>
  <%= @moderador.data_nasc %>
</p>

<p>
  <b>CPF:</b>
  <%= @moderador.cpf %>
</p>

<p>
  <b>RG:</b>
  <%= @moderador.rg %>
</p>

<p>
  <b>e-mail:</b>
  <%= @moderador.email %>
</p>


<%= link_to 'Edit', edit_moderador_path(@moderador) %> |
<%= link_to 'Back', moderadors_path %>

app/views/usuarios/_form.html.haml
= semantic_form_for(@usuario) do |f|
 = f.input :nome, :label => 'Nome'
 = f.input :sobrenome, :label => 'Sobrenome'
 = f.input :genero, :label => 'Genero'
 = f.input :data_nasc, :label => 'Data_Nasc'
 = f.input :email, :label => 'email'
 = f.input :senha, :label => 'Senha'

 = f.submit 'Salvar'

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Data nasc</th>
    <th>Genero</th>
    <th>Senha</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.nome %></td>
    <td><%= usuario.sobrenome %></td>
    <td><%= usuario.data_nasc %></td>
    <td><%= usuario.genero %></td>
    <td><%= usuario.senha %></td>
    <td><%= usuario.email %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Excluir', usuario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @usuario.nome %>
</p>

<p>
  <b>Sobrenome:</b>
  <%= @usuario.sobrenome %>
</p>

<p>
  <b>Data_Nasc:</b>
  <%= @usuario.data_nasc %>
</p>

<p>
  <b>Genero:</b>
  <%= @usuario.genero %>
</p>

<p>
  <b>Senha:</b>
  <%= @usuario.senha %>
</p>

<p>
  <b>email:</b>
  <%= @usuario.email %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>

app/views/vitaminas/_form.html.haml
= semantic_form_for(@vitamina) do |f|
 = f.input :nome, :label => 'Nome'
 = f.input :beneficio, :label => 'Beneficio'
 
 = f.submit 'Salvar'

app/views/vitaminas/edit.html.erb
<h1>Editing vitamina</h1>

<%= render 'form' %>

<%= link_to 'Show', @vitamina %> |
<%= link_to 'Back', vitaminas_path %>

app/views/vitaminas/index.html.erb
<h1>Listing vitaminas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Beneficio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vitaminas.each do |vitamina| %>
  <tr>
    <td><%= vitamina.nome %></td>
    <td><%= vitamina.beneficio %></td>
    <td><%= link_to 'Show', vitamina %></td>
    <td><%= link_to 'Edit', edit_vitamina_path(vitamina) %></td>
    <td><%= link_to 'Excluir', vitamina, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vitamina', new_vitamina_path %>

app/views/vitaminas/new.html.erb
<h1>New vitamina</h1>

<%= render 'form' %>

<%= link_to 'Back', vitaminas_path %>

app/views/vitaminas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @vitamina.nome %>
</p>

<p>
  <b>Beneficio:</b>
  <%= @vitamina.beneficio %>
</p>


<%= link_to 'Edit', edit_vitamina_path(@vitamina) %> |
<%= link_to 'Back', vitaminas_path %>